version: '3.9'

services:
  web:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: asdp_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Database=adsp;Username=postgres;Password=123
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: asdp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: adsp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
