name: CI/CD Pipeline

on:
  push:   
    branches:
      - main    
  pull_request: 
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        set -e  # Exit on any command failure
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Adding server host to known hosts: $SERVER_HOST"
        if ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts; then
          echo "Successfully added $SERVER_HOST to known_hosts"
        else
          echo "Failed to add $SERVER_HOST to known_hosts"
        exit 1
        fi

        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST << 'EOF'
          cd adsp
          docker compose down
          rm -rf asdp_final_project
          git clone https://github.com/vecktor21/asdp_final_project.git
          cd asdp_final_project
          sudo -s
          docker compose up --build -d
        EOF
